run:
  #tests: false
  skip-dirs:
    - vendor/
    - external/
    - bin/
    - datasets

linters:
  enable:
    - asasalint
    - asciicheck
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gofmt
    - wrapcheck
    - whitespace
    - wastedassign
    - varnamelen
    - usestdlibvars
    - unparam
    - unconvert
    - tparallel
    - thelper
    - testpackage
    - tenv
    - tagliatelle
    - predeclared
    - prealloc
    - nosprintfhostport
    - nonamedreturns
    - nolintlint
    #- nlreturn
    - nilnil
    - nilerr
    - nestif
    - nakedret
    - loggercheck
    - lll
    - ireturn
    - interfacebloat
    - importas
    - gosec
    - grouper
    - goimports
    - gofumpt
    - goerr113

linters-settings:
  errcheck:
    exclude-functions:
      - (*go.uber.org/zap.Logger).Sync

