port: 123
outputFolder: /tmp/forensibus
outputType: splunk
splunk:
  index: main
  # managementAddress: https://localhost:8089
  hec:
    address: http://localhost:8088
    token: 42424242-4242-4242-4242-424242424242
  # management:
  #   address: https://localhost:8089
  #   username: admin
  #   password: password

ArchivePasswords:
  - password
  - passwd