name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Get dependencies
        run: |
          go get -v .
          sudo apt-get install mingw-w64-x86-64-dev gcc-mingw-w64-x86-64 gcc-mingw-w64 make
          go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest

      - name: Install Musl
        run: |
          wget http://musl.libc.org/releases/musl-1.2.3.tar.gz
          tar -xvzf musl-1.2.3.tar.gz
          cd musl-1.2.3
          ./configure
          sudo make install
          cd ..

      - name: Make release note
        run: |
          git-chglog -o ${{ github.workspace }}-CHANGELOG.md ${{ github.ref_name }}

      - name: Build release
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.FORENSIBUS_TOKEN }}
          # generate_release_notes: true
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: |
            bin/forensibus_windows_amd64.exe
            bin/forensibus_windows_x86.exe
            bin/forensibus_linux_amd64

      # - name: Upload windows_amd64
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: forensibus_windows_amd64.exe
      #     path: bin/forensibus_windows_amd64.exe
      # - name: Upload windows_x86
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: forensibus_windows_x86.exe
      #     path: bin/forensibus_windows_x86.exe
      # - name: Upload linux_amd64
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: forensibus_linux_amd64
      #     path: bin/forensibus_linux_amd64
